{% set name = "daff" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47f0391eda7e2b5011f7ccac006b9178accb465bcb94a2c9f284257fff5d2686

build:
  entry_points:
    - daff=daff:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - test/test_example.py
  imports:
    - daff
  commands:
    - pip check
    - daff version
    - python test/test_example.py
  requires:
    - pip

about:
  home: https://github.com/paulfitz/daff
  dev_url: https://github.com/paulfitz/daff
  doc_url: https://paulfitz.github.io/daff
  summary: align and compare tables
  description: |
    This is a library for comparing tables, producing a summary of
    their differences, and using such a summary as a patch file.
  license: MIT
  license_file: LICENSE.md
  license_family: MIT

extra:
  recipe-maintainers:
    - rxm7706
