{% set name = "daff" %}
{% set version = "1.3.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/daff-{{ version }}.tar.gz
  sha256: 22d0da9fd6a3275b54c926a9c97b180f9258aad65113ea18f3fec52cbadcd818

build:
  entry_points:
    - daff=daff:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  #[py<38]

requirements:
  host:
    - python
    - pip
  run:
    - python
  run_constrained:
    - fibers >=3.0.0,<4.0.0
    - sqlite3 >=4.0.0,<5.0.0

test:
  source_files:
    - test/test_example.py
  imports:
    - daff
  commands:
    - pip check
    - python test/test_example.py
  requires:
    - pip

about:
  home: https://github.com/paulfitz/daff
  dev_url: https://github.com/paulfitz/daff
  doc_url: https://paulfitz.github.io/daff/
  summary: align and compare tables
  description: |
    This is a library for comparing tables, producing a summary of
    their differences, and using such a summary as a patch file.
  license: MIT
  license_file: LICENSE.md
  license_family: MIT

extra:
  recipe-maintainers:
    - rxm7706
